
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types';

const SUPABASE_URL = "https://irvrsqmgygrlmrqajjkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlydnJzcW1neWdybG1ycWFqamtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzYzNzUsImV4cCI6MjA1OTQ1MjM3NX0.NxGAKtH7MnWofXroeh9Ab3fgpwDpsaP4q3DKoswh5qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
